name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Update
        run: sudo apt-get update 
      - name: install ncurses
        run:  sudo apt-get install libncurses-dev
      - name: install sdl2
        run:  sudo apt-get install libsdl2-dev
      - name: install postgres
        run:  sudo apt-get install libpq-dev
  build:
    runs-on: ubuntu-22.04
    needs : install
    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make
